# Generated by Django 2.0.4 on 2018-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(blank=True, null=True, verbose_name='data da reserva'),
        ),
    ]
