# Generated by Django 2.0.4 on 2018-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180501_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffle',
            old_name='number_initial',
            new_name='initial_number',
        ),
    ]
