# Generated by Django 2.0.4 on 2018-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180501_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='initial_number',
            field=models.IntegerField(default=0, editable=False, verbose_name='número inicial'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='numbers',
            field=models.PositiveIntegerField(editable=False, verbose_name='números'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(editable=False, verbose_name='número'),
        ),
    ]
