# Generated by Django 2.0.4 on 2018-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180501_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='initial_number',
            field=models.IntegerField(default=0, verbose_name='número inicial'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='numbers',
            field=models.PositiveIntegerField(verbose_name='números'),
        ),
    ]
