# Generated by Django 2.0.4 on 2018-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180501_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
    ]
