# Generated by Django 2.0.4 on 2018-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_raffle_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='preço'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('raffle', 'number')},
        ),
    ]
