# Generated by Django 2.0.4 on 2018-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180502_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='draw_date',
            field=models.DateField(blank=True, null=True, verbose_name='data do sorteio'),
        ),
    ]
