# Generated by Django 2.0.4 on 2018-05-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_raffle_draw_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('number',)},
        ),
    ]
