# Generated by Django 2.0.4 on 2018-05-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180505_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('number',), 'verbose_name': 'bilhete', 'verbose_name_plural': 'bilhetes'},
        ),
    ]
