# Generated by Django 2.0.4 on 2018-06-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180622_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raffle', verbose_name='rifa'),
        ),
    ]
