# Generated by Django 2.0.4 on 2018-06-22 03:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180622_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço'),
        ),
    ]
